export const state = () => ({
  startObject: [
    {
      width: 1,
      height: 0.725,
      y: 1.1,
      x: 0.8,
      textSize: 1,
      content: 'Black Supper',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: true,
      pointer: false
    },
    {
      width: 1,
      height: 0.725,
      y: 1,
      x: 1,
      textSize: 1,
      content: 'Black Supper',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.25,
      y: 0.25,
      x: 1,
      textSize: 0.25,
      content: '††††††††††††††††††††††††††',
      align: 'center',
      color: 'white',
      tracking: 0.5,
      stroked: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.25,
      y: 5.5,
      x: 1,
      textSize: 0.25,
      content: '††††††††††††††††††††††††††',
      align: 'center',
      color: 'white',
      tracking: 0.5,
      stroked: false,
      pointer: false
    },
    {
      width: 0.66,
      height: 0.25,
      y: 0.65,
      x: 2.5,
      textSize: 0.1333,
      content: 'inspired by byron hughes & the last supper society',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true,
      pointer: false
    },
    {
      width: 0.66,
      height: 0.25,
      y: 3.5,
      x: 5.85,
      textSize: 0.08333,
      content: 'a blackletter typeface by yellow brick group',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true,
      pointer: false
    },
    /** {
      width: 0.1,
      height: 0.25,
      y: 3.93,
      x: 5,
      textSize: 0.08333,
      content: 'On Sale',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.15,
      height: 0.25,
      y: 4.07,
      x: 4.12,
      textSize: 0.25,
      content: '$30',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },**/
    {
      width: 0.5,
      height: 0.275,
      y: 3.625,
      x: 2.475,
      textSize: 0.333,
      content: 'Type here...',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false
    },
    {
      width: 0.233,
      height: 0.25,
      y: 4.9,
      x: 2.475,
      textSize: 0.1666,
      content: 'What\'s included?',
      align: 'left',
      color: 'white',
      tracking: 0.0,
      stroked: false,
      resize: false,
      layout: 'what'
    },
    {
      width: 0.4,
      height: 0.25,
      y: 4.9,
      x: 10.9,
      textSize: 0.1666,
      content: 'Instructions',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'why'
    },
    {
      width: 0.4,
      height: 0.31,
      y: 3.85,
      x: 11,
      textSize: 0.38,
      content: 'purchase now',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'buy'
    }
  ],
  whatObject: [
    {
      width: 0.75,
      height: 0.3,
      y: 0.2,
      x: 2.5,
      textSize: 0.3,
      content: 'What\'s Included?',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.025,
      height: 1.31,
      y: 1,
      x: 9.7,
      textSize: 0.35,
      content: '††††††††††††††',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.35,
      height: 0.4,
      y: 1.75,
      x: 2.6,
      textSize: 0.2,
      content: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.35,
      height: 0.4,
      y: 2.7,
      x: 2.6,
      textSize: 0.2,
      content: 'abcdefghijklmnopqrstuvwxyz',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.4,
      height: 0.325,
      y: 0.95,
      x: 1.62,
      textSize: 0.35,
      content: 'alphabet',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.25,
      height: 0.25,
      y: 3.3,
      x: 4.5,
      textSize: 0.2,
      content: 'numbers',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.3,
      height: 0.25,
      y: 3.7,
      x: 3.5,
      textSize: 0.2,
      content: '0123456789',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.38,
      height: 0.25,
      y: 4.3,
      x: 2,
      textSize: 0.25,
      content: 'punctuation',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.41,
      height: 0.25,
      y: 5,
      x: 1.5,
      textSize: 0.2,
      content: '.,:;"!?&@¶†‡*-–—()',
      align: 'right',
      color: 'white',
      tracking: 0.25,
      stroked: false,
      resize: true
    },
    /** {
      width: 0.45,
      height: 0.165,
      y: 5.35,
      x: 0.7,
      textSize: 0.1,
      content: '+ OVER 400 GLYPHS & DIACRITICS',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },**/
    {
      width: 0.35,
      height: 0.35,
      y: 1.25,
      x: 10.5,
      textSize: 0.3,
      content: 'Black Supper',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.25,
      height: 0.25,
      y: 1.6,
      x: 15.5,
      textSize: 0.155,
      content: 'in .otf & web',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.15,
      height: 0.25,
      y: 2.1,
      x: 10.5,
      textSize: 0.155,
      content: 'formats',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.37,
      height: 0.2,
      y: 2.15,
      x: 13.35,
      textSize: 0.12,
      content: '+ digital type specimen',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.45,
      height: 0.25,
      y: 2.75,
      x: 10.5,
      textSize: 0.135,
      content: '(single weight)',
      align: 'left',
      color: 'white',
      tracking: 0.25,
      stroked: false,
      resize: true
    },
    {
      width: 0.45,
      height: 0.25,
      y: 3.15,
      x: 10.5,
      textSize: 0.2,
      content: '-–———————————–-',
      align: 'left',
      color: 'white',
      tracking: 0.2,
      stroked: true,
      resize: true
    },
    {
      width: 0.45,
      height: 0.25,
      y: 5.75,
      x: 10.5,
      textSize: 0.2,
      content: '-–———————————–-',
      align: 'left',
      color: 'white',
      tracking: 0.2,
      stroked: true,
      resize: true
    }, /**
    {
      width: 0.35,
      height: 0.45,
      y: 3.5,
      x: 10.5,
      textSize: 0.45,
      content: 'free',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.5,
      height: 0.3,
      y: 3.3,
      x: 10.5,
      textSize: 0.3,
      content: 'trifold',
      align: 'left',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.35,
      height: 0.3,
      y: 5,
      x: 10.85,
      textSize: 0.15,
      content: 'zine to first 100 purchasers',
      align: 'right',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: true
    },**/
    {
      width: 0.425,
      height: 0.425,
      y: 4,
      x: 10.5,
      textSize: 0.1,
      content: ' ',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'zine'
    }
  ],
  howObject: [
    {
      width: 0.8,
      height: 0.25,
      y: 5.35,
      x: 2.9,
      textSize: 0.0666,
      content: 'Click "YOUTUBE" button on video to open in new tab & follow along!',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false
      // stroked: false,
      // resize: false,
      // pointer: false
    },
    {
      width: 1,
      height: 1.25,
      y: 0.9,
      x: 1,
      textSize: 0.8,
      content: 'Why Purchase?',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'video'
    }

  ],
  startMobile: [
    {
      width: 1,
      height: 0.35,
      y: 0.9,
      x: 0.8,
      textSize: 1,
      content: 'Black Supper',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: true,
      resize: false
    },
    {
      width: 1,
      height: 0.35,
      y: 0.8,
      x: 1,
      textSize: 1,
      content: 'Black Supper',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.15,
      y: 0.05,
      x: 1,
      textSize: 0.25,
      content: '††††††††††††††††††††††††††',
      align: 'center',
      color: 'white',
      tracking: 0.29,
      stroked: true,
      resize: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.15,
      y: 6,
      x: 1,
      textSize: 0.25,
      content: '††††††††††††††††††††††††††',
      align: 'center',
      color: 'white',
      tracking: 0.29,
      stroked: true,
      resize: false,
      pointer: false
    },
    {
      width: 0.8,
      height: 0.15,
      y: 0.45,
      x: 2.2,
      textSize: 0.1666,
      content: 'inspired by byron hughes & the last supper society',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.15,
      y: 1.7,
      x: 1,
      textSize: 0.17,
      content: 'a typeface by yellow brick group',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.9,
      height: 0.15,
      y: 2.1,
      x: 1,
      textSize: 0.4,
      content: 'On Sale',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.9,
      height: 0.3,
      y: 2.3,
      x: 1,
      textSize: 0.8,
      content: '$30',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    /* {
        width: 0.9,
        height: 0.25,
        y: 4.6,
        x: 1,
        textSize: 0.4,
        content: 'What\'s included?',
        align: 'center',
        color: 'white',
        tracking: 0,
        stroked: false,
        resize: false,
        layout: 'what'
      },
      {
        width: 0.9,
        height: 0.25,
        y: 4.5,
        x: 1,
        textSize: 0.4,
        content: 'Why purchase?',
        align: 'center',
        color: 'white',
        tracking: 0,
        stroked: false,
        resize: false,
        layout: 'why'
      }, */
    {
      width: 1,
      height: 0.25,
      y: 5.1,
      x: 0.5,
      textSize: 0.2,
      content: '* Visit on desktop to * experiment with Black Supper!',
      align: 'center',
      color: '#000',
      tracking: 0.2,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.9,
      height: 0.355,
      y: 3.3,
      x: 1,
      textSize: 0.6,
      content: 'purchase now',
      align: 'center',
      color: 'white',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'buy'
    }
  ]
})

export const mutations = {

}

export const actions = {

}
