export const state = () => ({
  startObject: [
    {
      width: 1,
      height: 0.725,
      y: 1.1,
      x: 0.8,
      textSize: 1,
      content: 'Ruta 23',
      align: 'center',
      color: '#008ff8',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 1,
      height: 0.725,
      y: 1,
      x: 1,
      textSize: 1,
      content: 'Ruta 23',
      align: 'center',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 1,
      height: 0.25,
      y: 0.25,
      x: 1,
      textSize: 0.25,
      content: '§§§§§§§§§§§§§§§§§§§§§§§§§§',
      align: 'center',
      color: '#ff5b49',
      tracking: 0.29,
      stroked: true,
      pointer: false
    },
    {
      width: 1,
      height: 0.25,
      y: 5.5,
      x: 1,
      textSize: 0.25,
      content: '§§§§§§§§§§§§§§§§§§§§§§§§§§',
      align: 'center',
      color: '#ff5b49',
      tracking: 0.29,
      stroked: true,
      pointer: false
    },
    {
      width: 0.66,
      height: 0.25,
      y: 1.05,
      x: 2.5,
      textSize: 0.1666,
      content: 'inspired by mexico city',
      align: 'left',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.66,
      height: 0.25,
      y: 3.5,
      x: 6,
      textSize: 0.08333,
      content: 'a monospaced typeface by yellow brick group',
      align: 'right',
      color: 'black',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.1,
      height: 0.25,
      y: 3.93,
      x: 5,
      textSize: 0.08333,
      content: 'On Sale',
      align: 'right',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.15,
      height: 0.25,
      y: 4.07,
      x: 4.12,
      textSize: 0.25,
      content: '$30',
      align: 'right',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.1,
      height: 0.35,
      y: 3.825,
      x: 3,
      textSize: 0.5,
      content: '®',
      align: 'center',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: false
    },
    {
      width: 0.4,
      height: 0.25,
      y: 4.9,
      x: 2.475,
      textSize: 0.1666,
      content: 'What\'s included?',
      align: 'left',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'what'
    },
    {
      width: 0.4,
      height: 0.25,
      y: 4.9,
      x: 10.9,
      textSize: 0.1666,
      content: 'Instructions',
      align: 'right',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'why'
    },
    {
      width: 0.65,
      height: 0.375,
      y: 3.7,
      x: 6.25,
      textSize: 0.4,
      content: 'purchase now',
      align: 'right',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: true,
      layout: 'buy'
    }
  ],
  whatObject: [
    {
      width: 0.75,
      height: 0.3,
      y: 0.2,
      x: 3.15,
      textSize: 0.25,
      content: 'What\'s Included?',
      align: 'center',
      color: '#008ff8',
      tracking: 0.2,
      stroked: false,
      resize: true
    },
    {
      width: 0.025,
      height: 1.31,
      y: 1,
      x: 9.7,
      textSize: 0.2,
      content: '/\\/\\/\\/\\/\\/\\/\\/\\/\\',
      align: 'center',
      color: '#008ff8',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.35,
      height: 0.4,
      y: 1.6,
      x: 2.6,
      textSize: 0.2,
      content: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
      align: 'right',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.4,
      height: 0.325,
      y: 0.95,
      x: 1.62,
      textSize: 0.35,
      content: 'ALPHABET',
      align: 'right',
      color: '#008ff8',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.25,
      height: 0.25,
      y: 2.9,
      x: 4.5,
      textSize: 0.2,
      content: 'numbers',
      align: 'right',
      color: '#008ff8',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.3,
      height: 0.25,
      y: 3.4,
      x: 3.5,
      textSize: 0.2,
      content: '0123456789',
      align: 'right',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.38,
      height: 0.25,
      y: 4.1,
      x: 2,
      textSize: 0.25,
      content: 'PUNCTUATION',
      align: 'right',
      color: '#008ff8',
      tracking: 0,
      stroked: true,
      resize: true
    },
    {
      width: 0.41,
      height: 0.25,
      y: 4.7,
      x: 1.5,
      textSize: 0.1,
      content: 'ꜜꜛ…¡¿·•‖/\\–—_‚„“”‘’«»‹›¢¤€£¥¶§©®™°|¦,:;!?*#()-\'$+=^%@&',
      align: 'right',
      color: 'black',
      tracking: 0.25,
      stroked: false,
      resize: true
    },
    {
      width: 0.45,
      height: 0.165,
      y: 5.35,
      x: 0.7,
      textSize: 0.1,
      content: '+ OVER 400 GLYPHS & DIACRITICS',
      align: 'right',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.35,
      height: 0.35,
      y: 1.25,
      x: 10.5,
      textSize: 0.3,
      content: 'RUTA 23',
      align: 'left',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.25,
      height: 0.25,
      y: 1.6,
      x: 15.5,
      textSize: 0.155,
      content: 'in .OTF & WEB',
      align: 'left',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.15,
      height: 0.25,
      y: 2.1,
      x: 10.5,
      textSize: 0.155,
      content: 'formats',
      align: 'left',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.37,
      height: 0.2,
      y: 2.15,
      x: 13.35,
      textSize: 0.12,
      content: '+ DIGITAL TYPE SPECIMEN',
      align: 'left',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.45,
      height: 0.25,
      y: 2.75,
      x: 10.5,
      textSize: 0.135,
      content: '(SINGLE WEIGHT)',
      align: 'left',
      color: 'black',
      tracking: 0.25,
      stroked: false,
      resize: true
    },
    {
      width: 0.45,
      height: 0.25,
      y: 3.15,
      x: 10.5,
      textSize: 0.4,
      content: '************',
      align: 'left',
      color: '#008ff8',
      tracking: 0.2,
      stroked: true,
      resize: true
    },
    {
      width: 0.45,
      height: 0.25,
      y: 5.75,
      x: 10.5,
      textSize: 0.4,
      content: '************',
      align: 'left',
      color: '#008ff8',
      tracking: 0.2,
      stroked: true,
      resize: true
    },
    {
      width: 0.35,
      height: 0.45,
      y: 3.5,
      x: 10.5,
      textSize: 0.45,
      content: 'FREE',
      align: 'left',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.5,
      height: 0.3,
      y: 4.3,
      x: 10.5,
      textSize: 0.3,
      content: '"EL PARQUE"',
      align: 'left',
      color: '#000',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.35,
      height: 0.3,
      y: 5,
      x: 10.85,
      textSize: 0.15,
      content: 'zine to first 100 purchasers',
      align: 'right',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: true
    },
    {
      width: 0.25,
      height: 0.825,
      y: 3.78,
      x: 16.65,
      textSize: 0.1,
      content: ' ',
      align: 'center',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'zine'
    }
  ],
  howObject: [
    {
      width: 1,
      height: 1.25,
      y: 1,
      x: 1,
      textSize: 0.8,
      content: 'Why Purchase?',
      align: 'center',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'video'
    }
  ],
  startMobile: [
    {
      width: 1,
      height: 0.35,
      y: 0.9,
      x: 0.8,
      textSize: 1,
      content: 'Ruta 23',
      align: 'center',
      color: '#008ff8',
      tracking: 0,
      stroked: true,
      resize: false
    },
    {
      width: 1,
      height: 0.35,
      y: 0.8,
      x: 1,
      textSize: 1,
      content: 'Ruta 23',
      align: 'center',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.15,
      y: 0.05,
      x: 1,
      textSize: 0.25,
      content: '§§§§§§§§§§§§§§§§§§§§§§§§§§',
      align: 'center',
      color: '#ff5b49',
      tracking: 0.29,
      stroked: true,
      resize: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.15,
      y: 6,
      x: 1,
      textSize: 0.25,
      content: '§§§§§§§§§§§§§§§§§§§§§§§§§§',
      align: 'center',
      color: '#ff5b49',
      tracking: 0.29,
      stroked: true,
      resize: false,
      pointer: false
    },
    {
      width: 0.8,
      height: 0.15,
      y: 0.45,
      x: 2.2,
      textSize: 0.1666,
      content: 'inspired by mexico city',
      align: 'center',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 1,
      height: 0.15,
      y: 1.7,
      x: 1,
      textSize: 0.17,
      content: 'a typeface by yellow brick group',
      align: 'center',
      color: 'black',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.9,
      height: 0.15,
      y: 2.1,
      x: 1,
      textSize: 0.4,
      content: 'On Sale',
      align: 'center',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.9,
      height: 0.25,
      y: 2.3,
      x: 1,
      textSize: 0.8,
      content: '$30',
      align: 'center',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      pointer: false
    },
    /* {
      width: 0.9,
      height: 0.25,
      y: 4.6,
      x: 1,
      textSize: 0.4,
      content: 'What\'s included?',
      align: 'center',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'what'
    },
    {
      width: 0.9,
      height: 0.25,
      y: 4.5,
      x: 1,
      textSize: 0.4,
      content: 'Why purchase?',
      align: 'center',
      color: '#ff5b49',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'why'
    }, */
    {
      width: 1,
      height: 0.25,
      y: 5.1,
      x: 0.5,
      textSize: 0.2,
      content: '* Visit on desktop to * experiment with RUTA 23!',
      align: 'center',
      color: '#000',
      tracking: 0.2,
      stroked: false,
      resize: false,
      pointer: false
    },
    {
      width: 0.9,
      height: 0.355,
      y: 3.3,
      x: 1,
      textSize: 0.6,
      content: 'purchase now',
      align: 'center',
      color: '#008ff8',
      tracking: 0,
      stroked: false,
      resize: false,
      layout: 'buy'
    }
  ]
})

export const mutations = {

}

export const actions = {

}
