<template lang="pug">
#acr-main
    CaseLeft(caseTitle='All City Riders' year='2018' :pattern='patterns.acr'  case='allcityriders' class='zTop')
        p(slot="description")
            |All City Riders is a new approach to the classic spin studio located in downtown Sacramento. The concept evolved from
            |ACR's desire to create a spin studio where all demographics in our city felt welcome. ACR believes the energy generated by the
            |people makes up our civic identity. We translated this into the visual approach by channeling the aesthetic of
            |New York City subways, an internationally recognized urban aesthetic and a subtle nod to graffiti artists going "All City".
            |Our partnership with ACR began with the creation of their brand identity
            |and continues to this day through photography, videography, social media curation, and community event activations.

    CaseRight(case='allcityriders')
        img(class='case-image' slot='image0' alt='acr1' src='../assets/img/cases/acr/1.jpg' id='all-city-riders1')
        hooper( :settings='hooperSettings' slot='image1' class='case-image' style="height: 100%" class='image-slider')
          slide
            img(class='case-image' alt='acr3' src='../assets/img/cases/acr/slide/s2.jpg' id='all-city-riders1')
          slide
            img(class='case-image' alt='acr4' src='../assets/img/cases/acr/slide/s1.jpg' id='all-city-riders2')
          slide
            img(class='case-image' alt='acr4' src='../assets/img/cases/acr/slide/s3.jpg' id='all-city-riders2')
          slide
            img(class='case-image' alt='acr4' src='../assets/img/cases/acr/slide/s4.jpg' id='all-city-riders2')
          hooper-navigation(slot="hooper-addons")
        video(class='case-image' slot='image2' alt='acr1' src='../assets/img/cases/acr/2.mp4' id='all-city-riders1' controls muted loop poster="../assets/img/posters/acr1.jpg")
        img(class='case-image' slot='image3' alt='acr1' src='../assets/img/cases/acr/3.jpg' id='all-city-riders1')
        img(class='case-image' slot='image4' alt='acr1' src='../assets/img/cases/acr/4.jpg' id='all-city-riders1')
        img(class='case-image' slot='image5' alt='acr1' src='../assets/img/cases/acr/5.jpg' id='all-city-riders1')
        img(class='case-image' slot='image6' alt='acr1' src='../assets/img/cases/acr/6.gif' id='all-city-riders1')
        img(class='case-image' slot='image7' alt='acr1' src='../assets/img/cases/acr/7.jpg' id='all-city-riders1')
        img(class='case-image-last' slot='image8' alt='acr1' src='../assets/img/cases/acr/8.jpg' id='all-city-riders1')

        img( alt='acr1' slot='z1' src='../assets/img/cases/acr/card1.png' id='z1' class='hide-on-ipad')
        img( alt='acr1' slot='z1' src='../assets/img/cases/acr/card2.png' id='z2' class='hide-on-ipad')
        img( alt='acr1' slot='z1' src='../assets/img/cases/acr/card1.png' id='z3' class='hide-on-ipad')
        img( alt='acr1' slot='z1' src='../assets/img/cases/acr/card2.png' id='z4' class='hide-on-ipad')
</template>

<script>

import { Hooper, Slide, Navigation as HooperNavigation } from 'hooper'
import CaseLeft from '../components/cases/CaseLeft.vue'
import CaseRight from '../components/cases/CaseRight.vue'
import 'hooper/dist/hooper.css'

export default {
  name: 'AllCityRiders',
  components: {
    CaseLeft,
    CaseRight,
    Hooper,
    Slide,
    HooperNavigation
  },
  data () {
    return {
      patterns: {
        acr: [1, 1, 0, 1, 0, 1, 1, 1, 0]
      },
      hooperSettings: {
        itemsToShow: 1,
        centerMode: true,
        infiniteScroll: true,
        wheelControl: false
      }
    }
  },
  methods: {

  }
}

</script>

<style scoped lang="stylus">
zTop
  position relative

*
  margin: 0px
  padding 0px

#acr-main
  font-family: 'Avenir', Helvetica, Arial, sans-serif
  -webkit-font-smoothing: antialiased
  -moz-osx-font-smoothing: grayscale
  color: #2c3e50
  transition: 1s
  width:100%
  height:100%

.case-image
    width:100%
    padding-bottom: 20px

.case-image-last
    width:100%
    padding-bottom: 0px

#z1
  position absolute
  top 98%
  left 0
  padding-left 24%
  z-index 1000
  height 25%

#z2
  position absolute
  top 192%
  left 0
  padding-left 30%
  z-index 1000
  height 25%

#z3
  position absolute
  top 320%
  left 0
  padding-left 20%
  z-index 1000
  height 25%

#z4
  position absolute
  top 396%
  left 0
  padding-left 32%
  z-index 1000
  height 25%
</style>
